---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAPには、信頼性の高い操作を提供するために、AWS でのストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。 
---
= AWS のCloud Volumes ONTAPのストレージ制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、信頼性の高い操作を実現するためのストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。



== ライセンスによる最大システム容量

最大システム容量には、ディスクベースのストレージと、データ階層化に使用されるオブジェクト ストレージが含まれます。

NetApp はシステム容量制限の超過をサポートしていません。ライセンス容量の制限に達した場合、 BlueXP はアクションが必要なメッセージを表示し、追加のディスクを追加できなくなります。

一部の構成では、ディスク制限により、ディスクのみを使用して容量制限に達することができません。このような場合、容量制限に達するには https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]。詳細については、以下の容量とディスク制限を参照してください。

.容量ベースのライセンスの容量制限
容量ベースのライセンスにより、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された合計容量は、クラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。参照 https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWSのドキュメント"^]詳細についてはこちらをご覧ください。

他のライセンスタイプの容量制限::


[cols="25,75"]
|===
| ライセンス | 最大システム容量（ディスク + オブジェクト ストレージ） 


| フリーミアム | 500ギガバイト 


| PAYGO 探索 | 2 TiB (Explore ではデータ階層化はサポートされていません) 


| PAYGOスタンダード | 10TiB 


| PAYGOプレミアム | 368 TiB 


| ノードベースのライセンス | 2 PiB（複数のライセンスが必要） 
|===
.HA の場合、ライセンス容量の制限はノードごとですか、それとも HA ペア全体に対してですか?
容量制限は HA ペア全体に適用されます。ノードごとではありません。たとえば、プレミアム ライセンスでは、両方のノードで最大 368 TiB が許可されます。

.AWS の HA システムの場合、ミラーリングされたデータは容量制限にカウントされますか?
いいえ、違います。AWS HA ペアのデータはノード間で同期的にミラーリングされるため、障害発生時にもデータを利用できます。たとえば、ノード A で 8 TiB のディスクを購入した場合、 BlueXP はミラーリングされたデータに使用されるノード B にも 8 TiB のディスクを割り当てます。  16 TiB の容量がプロビジョニングされましたが、ライセンス制限にカウントされるのは 8 TiB のみです。



== アグリゲートの制限

Cloud Volumes ONTAP はEBS ボリュームをディスクとして使用し、それらを _アグリゲート_ にグループ化します。アグリゲートはボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限 


| 集約の最大数 | 単一ノード: ディスク制限と同じ HA ペア: ノードあたり 18 個 ^1^ 


| 最大集約サイズ ^2^  a| 
* 96 TiBの生の容量
* エラスティックボリュームによる 128 TiB の生の容量 ^3^




| アグリゲートあたりのディスク数 ^4^  a| 
* 1-6
* 1-8 弾性ボリューム付き ^3^




| アグリゲートあたりの RAID グループの最大数 | 1 
|===
注：

. データ ディスクの制限を超えてしまうため、HA ペアの両方のノードに 18 個のアグリゲートを作成することはできません。
. 最大集約サイズはディスクによって異なり、データ階層化に使用するオブジェクト ストレージは含まれません。
. Amazon EBS Elastic Volumes 機能をサポートする構成の場合、アグリゲートには最大 8 個のディスクを含めることができ、最大 128 TiB の容量が提供されます。デフォルトでは、 Cloud Volumes ONTAP 9.11.0 以降のシステムでは、gp3 または io1 ディスクを使用する場合、Amazon EBS Elastic Volumes が有効になっています。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["エラスティックボリュームのサポートについて詳しくはこちら"^]
. アグリゲート内のすべてのディスクは同じサイズである必要があります。




== EC2 インスタンスごとのディスクと階層化の制限

容量制限は、使用する EC2 インスタンスタイプファミリーと、単一ノードシステムを使用しているか HA ペアを使用しているかによって異なります。

以下の注記には、以下の表に表示される数字に関する詳細が記載されています。

* ディスク制限は、ユーザー データが含まれるディスクに固有です。
+
制限にはブート ディスクとルート ディスクは含まれません。

* ディスクのみを使用する場合と、ディスクとオブジェクト ストレージへのコールド データ階層化を使用する場合の最大システム容量がリストされます。
* Cloud Volumes ONTAP はEBS ボリュームをディスクとして使用し、最大ディスク サイズは 16 TiB です。




=== 容量ベースのライセンスのさまざまな展開モードの制限

容量ベースのライセンス パッケージを使用するCloud Volumes ONTAPシステムには、次のディスク制限が適用されます。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAPのライセンスオプションについて学ぶ"^]


NOTE: 単一ノードおよびHA構成の最大システム容量とデータ階層化容量の制限については、以下を参照してください。<<cap-license-aws>> 。



==== シングル ノード

[cols="18,18,32,width=100%,options="]
|===


| 実例 | ノードあたりの最大ディスク数 | ディスクのみの最大システム容量 


| c5、m5、r5インスタンス | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304 TiB 
|===
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== HAペア

[cols="18,18,32,width=100%,options="]
|===


| 実例 | ノードあたりの最大ディスク数 | ディスクのみの最大システム容量 


| c5、m5、r5インスタンス | 18 | 288 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^1^ | 256TiB 
|===
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




=== ノードベースライセンスのさまざまな展開モードの制限

次のディスク制限は、ノードベースのライセンスを使用するCloud Volumes ONTAPシステムに適用されます。これは、ノードごとにCloud Volumes ONTAP のライセンスを取得できる前世代のライセンス モデルです。ノードベースのライセンスは、既存のお客様にも引き続きご利用いただけます。

Cloud Volumes ONTAP BYOL シングルノードまたは HA ペア システムの複数のノードベースのライセンスを購入して、テスト済みおよびサポートされている最大システム容量制限である 2 PiB まで、368 TiB を超える容量を割り当てることができます。ディスク制限により、ディスクのみを使用すると容量制限に到達できなくなる可能性があることに注意してください。ディスク制限を超えるには https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAPに追加のシステムライセンスを追加する方法を学びます"^] 。Cloud Volumes ONTAP は、テスト済みおよびサポート済みの最大システム容量である 2 PiB までをサポートしますが、2 PiB の制限を超えると、サポートされないシステム構成になります。

AWS Secret Cloud および Top Secret Cloud リージョンでは、Cloud Volumes ONTAP 9.12.1 以降、複数のノードベースのライセンスの購入がサポートされています。



==== PAYGOプレミアム付きシングルノード

[cols="18,18,32,32"]
|===
| 実例 | ノードあたりの最大ディスク数 | ディスクのみの最大システム容量 | ディスクとデータ階層化による最大システム容量 


| c5、m5、r5インスタンス | 21 ^1^ | 336 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB 
|===
. Cloud Volumes ONTAPの新規展開では、21 個のデータ ディスクが制限となります。バージョン 9.7 以前で作成されたシステムをアップグレードする場合、システムは引き続き 22 個のディスクをサポートします。  9.8 リリース以降、コア ディスクが追加されたため、これらのインスタンス タイプを使用する新しいシステムではサポートされるデータ ディスクが 1 つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== BYOL による単一ノード

[cols="18,18,16,16,16,16"]
|===
| 実例 | ノードあたりの最大ディスク数 2+| 1つのライセンスで最大のシステム容量 2+| 複数のライセンスで最大のシステム容量 


2+|  | *ディスクのみ* | *ディスク + データ階層化* | *ディスクのみ* | *ディスク + データ階層化* 


| c5、m5、r5インスタンス | 21 ^1^ | 336 TiB | 368 TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB | 304 TiB | 2 PiB 
|===
. Cloud Volumes ONTAPの新規展開では、21 個のデータ ディスクが制限となります。バージョン 9.7 以前で作成されたシステムをアップグレードする場合、システムは引き続き 22 個のディスクをサポートします。  9.8 リリース以降、コア ディスクが追加されたため、これらのインスタンス タイプを使用する新しいシステムではサポートされるデータ ディスクが 1 つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== HAはPAYGOプレミアムとペアリングします

[cols="18,18,32,32"]
|===
| 実例 | ノードあたりの最大ディスク数 | ディスクのみの最大システム容量 | ディスクとデータ階層化による最大システム容量 


| c5、m5、r5インスタンス | 18 ^1^ | 288 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256TiB | 368 TiB 
|===
. Cloud Volumes ONTAPの新規展開では、18 個のデータ ディスクが制限となります。バージョン 9.7 以前で作成されたシステムをアップグレードする場合、システムは引き続き 19 個のディスクをサポートします。  9.8 リリース以降、コア ディスクが追加されたため、これらのインスタンス タイプを使用する新しいシステムではサポートされるデータ ディスクが 1 つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




==== HA と BYOL のペア

[cols="18,18,16,16,16,16"]
|===
| 実例 | ノードあたりの最大ディスク数 2+| 1つのライセンスで最大のシステム容量 2+| 複数のライセンスで最大のシステム容量 


2+|  | *ディスクのみ* | *ディスク + データ階層化* | *ディスクのみ* | *ディスク + データ階層化* 


| c5、m5、r5インスタンス | 18 ^1^ | 288 TiB | 368 TiB | 288 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256TiB | 368 TiB | 256TiB | 2 PiB 
|===
. Cloud Volumes ONTAPの新規展開では、18 個のデータ ディスクが制限となります。バージョン 9.7 以前で作成されたシステムをアップグレードする場合、システムは引き続き 19 個のディスクをサポートします。  9.8 リリース以降、コア ディスクが追加されたため、これらのインスタンス タイプを使用する新しいシステムではサポートされるデータ ディスクが 1 つ少なくなります。
. このインスタンス タイプには他のインスタンス タイプよりも多くのローカル NVMe ディスクがあるため、サポートされるデータ ディスクの数は少なくなります。




== ストレージVMの制限

一部の構成では、Cloud Volumes ONTAP用の追加のストレージ VM (SVM) を作成できます。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["追加のストレージVMを作成する方法を学ぶ"^] 。

[cols="40,60"]
|===
| ライセンス タイプ | ストレージVMの制限 


| *フリーミアム*  a| 
合計 24 台のストレージ VM ^1,2^



| *容量ベースのPAYGOまたはBYOL* ^3^  a| 
合計 24 台のストレージ VM ^1,2^



| *ノードベースのPAYGO*  a| 
* データを提供するための 1 つのストレージ VM
* 災害復旧用のストレージVM 1台




| *ノードベースのBYOL* ^4^  a| 
* 合計 24 台のストレージ VM ^1,2^


|===
. 使用する EC2 インスタンスタイプによっては、制限が低くなる場合があります。インスタンスごとの制限については、以下のセクションに記載されています。
. これら 24 台のストレージ VM は、データを提供したり、災害復旧 (DR) 用に構成したりできます。
. 容量ベースのライセンスの場合、追加のストレージ VM に対して追加のライセンス コストは発生しませんが、ストレージ VM ごとに 4 TiB の最小容量料金が発生します。たとえば、2 つのストレージ VM を作成し、それぞれに 2 TiB のプロビジョニングされた容量がある場合、合計 8 TiB が課金されます。
. ノードベースの BYOL の場合、 Cloud Volumes ONTAPにデフォルトで付属する最初のストレージ VM を超える追加のデータ提供ストレージ VM ごとにアドオン ライセンスが必要です。ストレージ VM アドオン ライセンスを取得するには、アカウント チームにお問い合わせください。
+
災害復旧 (DR) 用に構成するストレージ VM にはアドオン ライセンスは必要ありません (無料) が、ストレージ VM の制限にカウントされます。たとえば、データ サービス ストレージ VM が 12 台、災害復旧用にストレージ VM が 12 台構成されている場合、制限に達しているため、追加のストレージ VM を作成することはできません。





=== EC2 インスタンスタイプによるストレージ VM の制限

追加のストレージ VM を作成する場合は、ポート e0a にプライベート IP アドレスを割り当てる必要があります。以下の表は、インターフェースあたりのプライベート IP の最大数と、 Cloud Volumes ONTAP がデプロイされた後にポート e0a で使用できる IP アドレスの数を示しています。使用可能な IP アドレスの数は、その構成のストレージ VM の最大数に直接影響します。

以下にリストされているインスタンスは、c5、m5、および r5 インスタンス ファミリ用です。

[cols="6*"]
|===
| 構成 | インスタンスタイプ | インターフェースあたりの最大プライベート IP | 展開後に残る IP 数 ^1^ | 管理 LIF なしの最大ストレージ VM 数 ^2,3^ | 管理 LIF を備えた最大ストレージ VM 数 ^2,3^ 


.9+| *単一ノード* | *.特大 | 15 | 9 | 10 | 5 


| *.2xlarge | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *単一 AZ の HA ペア* | *.特大 | 15 | 10 | 11 | 5 


| *.2xlarge | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *マルチAZのHAペア* | *.特大 | 15 | 12 | 13 | 13 


| *.2xlarge | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. この数値は、Cloud Volumes ONTAPがデプロイおよびセットアップされた後、ポート e0a で使用できる残りのプライベート IP アドレスの数を示します。たとえば、*.2xlarge システムは、ネットワーク インターフェイスごとに最大 15 個の IP アドレスをサポートします。 HA ペアを単一の AZ に展開すると、ポート e0a に 5 つのプライベート IP アドレスが割り当てられます。その結果、*.2xlarge インスタンス タイプを使用する HA ペアには、追加のストレージ VM 用に 10 個のプライベート IP アドレスが残ります。
. これらの列にリストされている数には、 BlueXP がデフォルトで作成する初期ストレージ VM が含まれます。たとえば、この列に 24 と表示されている場合は、合計 24 台の追加ストレージ VM を 23 台作成できることを意味します。
. ストレージ VM の管理 LIF はオプションです。管理 LIF は、 SnapCenterなどの管理ツールへの接続を提供します。
+
プライベート IP アドレスが必要であるため、作成できる追加のストレージ VM の数が制限されます。唯一の例外は、複数の AZ の HA ペアです。その場合、管理 LIF の IP アドレスは _フローティング_ IP アドレスなので、_プライベート_ IP 制限にはカウントされません。





== ファイルとボリュームの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限 


.2+| *ファイル* | 最大サイズ ^2^ | 128 TB 


| ボリュームあたりの最大数 | ボリューム サイズに依存、最大20億個 


| * FlexCloneボリューム* | 階層的クローンの深さ ^1^ | 499 


.3+| * FlexVolボリューム* | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ ^3^ | 300TiB 


| *Qtrees* | FlexVolあたりの最大数 | 4,995 


| *スナップショットコピー* | FlexVolあたりの最大数 | 1,023 
|===
. 階層クローンの深さは、単一のFlexVol volumeから作成できるFlexCloneボリュームのネストされた階層の最大深さです。
. ONTAP 9.12.1P2以降では、上限は128TBです。ONTAP 9.11.1以前のバージョンでは、上限は16TBです。
. 最大サイズ 300 TiB までのFlexVol volumeの作成は、次のツールと最小バージョンを使用してサポートされます。
+
** Cloud Volumes ONTAP 9.12.1 P2 および 9.13.0 P2 以降の System Manager およびONTAP CLI
** Cloud Volumes ONTAP 9.13.1 以降のBlueXP






== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSIストレージ | パラメータ | 制限 


.4+| *LUN* | ノードあたりの最大数 | 1,024 


| LUNマップの最大数 | 1,024 


| 最大サイズ | 16TiB 


| ボリュームあたりの最大数 | 512 


| *igroups* | ノードあたりの最大数 | 256 


.2+| *イニシエーター* | ノードあたりの最大数 | 512 


| igroupあたりの最大数 | 128 


| *iSCSIセッション* | ノードあたりの最大数 | 1,024 


.2+| *LIF* | ポートあたりの最大数 | 32 


| ポートセットあたりの最大数 | 32 


| *ポートセット* | ノードあたりの最大数 | 256 
|===