---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.16.1 には新しい機能強化が含まれています。 
---
= Cloud Volumes ONTAP 9.16.1 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.16.1 には新しい機能強化が含まれています。

新しいCloud Volumes ONTAP機能も、 NetApp Consoleの最新バージョンに導入されています。詳細については、 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^] コンソールで管理されます。



== 9.16.1 P8（2025年10月16日）

Cloud Volumes ONTAP 9.16.1 P8 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P8["P8パッチで修正されたバグのリストを見る"^](NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P7（2025年10月9日）

Cloud Volumes ONTAP 9.16.1 P7 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P7["P7パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P6（2025年10月9日）

Cloud Volumes ONTAP 9.16.1 P6 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P6["P6パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P5（2025年7月28日）

Cloud Volumes ONTAP 9.16.1 P5 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P5["P5パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P4（2025年7月8日）

Cloud Volumes ONTAP 9.16.1 P4 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P4["P4パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P3（2025年5月29日）

Cloud Volumes ONTAP 9.16.1 P3 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3["P3パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P2（2025年4月17日）

Cloud Volumes ONTAP 9.16.1 P2 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2["P2パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 P1（2025年4月17日）

Cloud Volumes ONTAP 9.16.1 P1 パッチが、すべてのクラウド プロバイダーでアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1["P1パッチで修正されたバグのリストを見る"^] (NetAppサポート サイトへのログインが必要です)。



== 9.16.1 GA（2025年3月6日）

Cloud Volumes ONTAP 9.16.1 一般提供リリースが、AWS、Azure、Google Cloud での展開およびアップグレードに利用できるようになりました。



== アップグレードノート

このリリースへのアップグレードの詳細については、これらのメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAPのアップグレードはコンソールから完了する必要があります。System Manager または CLI を使用してCloud Volumes ONTAP をアップグレードしないでください。システムの安定性に影響を与える可能性があります。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["コンソールから通知があった場合にアップグレードする方法を学びます"^]。



=== サポートされているアップグレード パス

AWS、Azure、Google Cloud の 9.15.1 リリースからCloud Volumes ONTAP 9.16.1 にアップグレードできます。コンソールでは、対象となるCloud Volumes ONTAPシステムをこのリリースにアップグレードするように求められます。



=== ダウンタイム

* 単一ノード システムをアップグレードすると、システムが最大 25 分間オフラインになり、その間に I/O が中断されます。
* HA ペアのアップグレードは中断を伴わず、I/O も中断されません。この中断のないアップグレード プロセスでは、各ノードが同時にアップグレードされ、クライアントへの I/O の提供が継続されます。

