---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud では、いくつかのCloud Volumes ONTAP構成がサポートされています。 
---
= Google Cloud でサポートされているCloud Volumes ONTAPの構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud では、いくつかのCloud Volumes ONTAP構成がサポートされています。



== ライセンスによってサポートされる構成

Cloud Volumes ONTAP は、 Google Cloud で単一ノード システムとして、またフォールト トレランスと無停止運用を実現する高可用性 (HA) ノード ペアとして利用できます。

単一ノード システムを HA ペアにアップグレードすることはサポートされていません。単一ノード システムと HA ペア間を切り替える場合は、新しいシステムを展開し、既存のシステムから新しいシステムにデータを複製する必要があります。

Cloud Volumes ONTAP は、クラウド プロバイダーの予約済み VM インスタンスまたはオンデマンド VM インスタンスのいずれかで実行できます。他の VM インスタンス タイプを使用するソリューションはサポートされていません。

[role="tabbed-block"]
====
.容量ベースのライセンス
--
[cols="h,d,d,d"]
|===
|  | フリーミアム | 最適化されました ^4^ | 容量ベースのライセンス（Essentials および Professional） 


| 最大システム容量（ディスク + オブジェクト ストレージ） | 500ギガバイト  a| 
容量ベースのライセンスにより、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された合計容量は、クラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。



| サポートされているマシンタイプ ^1^  a| 
* n1-標準-8 ^1^
* n1-標準-32 ^1^
* n2-標準-4
* n2-標準-8
* n2-標準-16
* n2-標準-32
* n2-標準-48
* n2-標準-64

 a| 
* n2-標準-4
* n2-標準-8

 a| 
* n1-標準-8 ^1^
* n1-標準-32 ^1^
* n2-標準-4
* n2-標準-8
* n2-標準-16
* n2-標準-32
* n2-標準-48
* n2-標準-64




| サポートされているディスクの種類 ^2^ 3+| バランス永続ディスク ^3^、パフォーマンス (SSD) 永続ディスク ^3^、および標準 (HDD) 永続ディスク。 
|===
注：

. ^1^ Google Cloud でCloud Volumes ONTAPの新しいインスタンスをデプロイするときに、n1 シリーズのマシンはBlueXPで選択できなくなりました。  n1 シリーズのマシンは、古い既存のシステムでのみ保持され、サポートされます。  Cloud Volumes ONTAPの新しいデプロイメントは、Google Cloud 9.8 リリース以降でのみサポートされます。 Cloud Volumes ONTAP 9.8 以降と互換性のある n2 シリーズ マシンに切り替えることをお勧めします。ただし、n1 シリーズのマシンは、API を通じて行われる新しい展開では利用できるようになります。
+
custom-4-16384 マシン タイプは、新しいCloud Volumes ONTAPシステムではサポートされなくなりました。このマシン タイプで既存のシステムを実行している場合は、それを使い続けることもできますが、n2-standard-4 マシン タイプに切り替えることをお勧めします。

. ^2^ ディスク制限により、ディスクのみを使用して最大システム容量制限に達するのを防ぐことができます。容量制限に達するには https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]。
+
link:reference-limits-gcp.html["Google Cloud のディスク制限について詳しくは"] 。

. ^3^ バランス永続ディスクとパフォーマンス (SSD) 永続ディスクを使用すると、拡張書き込みパフォーマンスが有効になります。
+
Cloud Volumes ONTAP 9.13.0 以降では、次の HA ペア展開インスタンスで、_Flash Cache_、高速書き込み、および 8,896 バイトの最大転送単位 (MTU) の上限が利用できるようになります。

+
** n2-標準-16
** n2-標準-32
** n2-標準-48
** n2-標準-64
+
適切なインスタンス タイプをデプロイするときに、_Flash Cache_ と高速書き込みを有効にできます。  8,896 バイトの最大伝送単位を有効にするには、デプロイメントに VPC-1、VPC-2、または VPC-3 を選択する必要があります。 MTU が大きいほど、ネットワーク スループットが高くなります。これらのデプロイメントの起動の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google Cloud で HA ペアを起動する"] 。

+

NOTE: _フラッシュ キャッシュ_、高書き込みモード、および 8,896 の MTU は機能に依存しており、構成されたインスタンス内で個別に無効にすることはできません。



. ^4^ 2025 年 8 月 11 日以降、 Cloud Volumes ONTAP Optimized ライセンスは非推奨となり、従量課金制 (PAYGO) サブスクリプションの Google Cloud マーケットプレイスで購入または更新できなくなります。詳細については、 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAPの新機能"^] 。


--
.ノードベースのライセンス
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO 探索 | PAYGOスタンダード | PAYGOプレミアム | ノードベースのBYOL 


| 最大システム容量（ディスク + オブジェクト ストレージ） | 2TB ^2^ | 10TiB | 368 TiB | ライセンスあたり368 TiB 


| サポートされているマシンタイプ ^3^  a| 
* n2-標準-4

 a| 
* n1-標準-8 ^3^
* n2-標準-8

 a| 
* n1-標準-32 ^3^
* n2-標準-16
* n2-標準-32
* n2-標準-48
* n2-標準-64

 a| 
* n1-標準-8 ^3^
* n1-標準-32 ^3^
* n2-標準-4
* n2-標準-8
* n2-標準-16
* n2-標準-32
* n2-標準-48
* n2-標準-64




| サポートされているディスクの種類 4+| バランス永続ディスク ^4^、パフォーマンス (SSD) 永続ディスク ^4^、および標準 (HDD) 永続ディスク。 
|===
注：

. ^1^ ディスク制限により、ディスクのみを使用して最大システム容量制限に達するのを防ぐことができます。容量制限に達するには https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]。
+
link:reference-limits-gcp.html["Google Cloud のディスク制限について詳しくは"] 。

. ^2^ Google Cloud Storage へのデータ階層化は PAYGO Explore ではサポートされていません。
. ^3^ Google Cloud でCloud Volumes ONTAPの新しいインスタンスをデプロイするときに、n1 シリーズのマシンはBlueXPで選択できなくなりました。  n1 シリーズのマシンは、古い既存のシステムでのみ保持され、サポートされます。  Cloud Volumes ONTAPの新しいデプロイメントは、Google Cloud 9.8 リリース以降でのみサポートされます。 Cloud Volumes ONTAP 9.8 以降と互換性のある n2 シリーズ マシンに切り替えることをお勧めします。ただし、n1 シリーズのマシンは、API を通じて実行される新しいデプロイメントに使用できます。
+
custom-4-16384 マシン タイプは、新しいCloud Volumes ONTAPシステムではサポートされなくなりました。このマシン タイプで既存のシステムを実行している場合は、それを使い続けることもできますが、n2-standard-4 マシン タイプに切り替えることをお勧めします。

. ^4^ バランス永続ディスクとパフォーマンス (SSD) 永続ディスクを使用すると、拡張書き込みパフォーマンスが有効になります。


BlueXPインターフェースには、Standard および BYOL でサポートされている追加のマシン タイプ n1-highmem-4 が表示されます。ただし、このマシンタイプは実稼働環境向けではありません。特定のラボ環境でのみ利用できるようにしました。

Cloud Volumes ONTAPソフトウェア バージョン 9.13.0 以降では、次の HA ペア展開インスタンスで、_Flash Cache_、高速書き込み、および 8,896 バイトの最大転送単位 (MTU) の上限が利用できるようになります。

* n2-標準-16
* n2-標準-32
* n2-標準-48
* n2-標準-64


適切なインスタンス タイプをデプロイするときに、_Flash Cache_ と高速書き込みを有効にできます。  8,896 バイトの最大伝送単位を有効にするには、デプロイメントに VPC-1、VPC-2、または VPC-3 を選択する必要があります。 MTU が大きいほど、ネットワーク スループットが高くなります。これらのデプロイメントの起動の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google Cloud で HA ペアを起動する"] 。


NOTE: _フラッシュ キャッシュ_、高書き込みモード、および 8,896 の MTU は機能に依存しており、構成されたインスタンス内で個別に無効にすることはできません。

--
====
特定のマシンタイプの詳細については、Google Cloud のドキュメントを参照してください。

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1シリーズ汎用機"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2シリーズ汎用機"^]




== サポートされているディスクサイズ

Google Cloud では、アグリゲートにはタイプとサイズがすべて同じ最大 6 個のディスクを含めることができます。次のディスク サイズがサポートされています。

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== サポートされている地域

Google Cloud のリージョンサポートについては、 https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes グローバルリージョン"^] 。
