---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: このページでは、 NetAppがクラウド プロバイダーと連携して、発生する可能性のある問題を解決する方法について説明します。 
---
= Cloud Volumes ONTAPのクラウド プロバイダーとの連携
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppがクラウド プロバイダーと連携して潜在的な問題に対処する方法について説明します。



== 共同サポートのベストプラクティス

NetApp はライセンシーにサポートを提供することを約束しており、ライセンシーから報告されたCloud Volumes ONTAPのテクニカル サポート問題を解決するために商業的に合理的な努力を払います。  NetAppと該当するクラウド プロバイダーは、相互のライセンス ソフトウェアまたはインフラストラクチャに対して直接的なサポート義務を負いません。

NetApp は、該当するクラウド プロバイダーのサービスに起因する可能性のある顧客の技術的な問題について、該当するクラウド プロバイダーに連絡することを目的としたツールを実装しています。ただし、シームレスなサポート フローを維持するための最善の方法は、お客様が (i) NetAppと該当するクラウド プロバイダーの両方と現在のサポート契約を維持し、(ii) 技術的な問題が発生し、どの製品またはサービスがそれらの技術的な問題の原因であるかをお客様が明確に把握する必要がある場合に、 NetAppと該当するクラウド プロバイダーの両方と共同エスカレーション ミーティングを調整することです。



== Azure メンテナンス イベント

Microsoft は、Cloud Volumes ONTAP VM に影響を及ぼす可能性のある Azure 仮想マシン (VM) インフラストラクチャのメンテナンス イベントをスケジュールし、プログラムで通知します。これらのイベントは、メンテナンス ウィンドウの 15 分前に発表されます。

Cloud Volumes ONTAP高可用性 (HA) ペアでは、メンテナンス イベントの特別な処理がサポートされています。アプリケーションの健全性を維持するために、安定性を優先する予防的なテイクオーバーを実行します。15 秒を超える接続の損失により、フェイルオーバー機能が無効になります。

メンテナンス ウィンドウがアナウンスされると、対象ノードのパートナー ノードがテイクオーバーを実行します。メンテナンスが完了すると、ギブバックが開始されます。ギブバック後、HA ペアは正常な状態に戻ると予想されます。これが発生しない場合は、 NetAppサポートにお問い合わせください。メンテナンス イベントは一度に HA ペアの VM の 1 つを対象とし、通常は比較的短い期間に両方のノードが対象となることに注意してください。

Cloud Volumes ONTAPの非継続的可用性CIFS共有を使用するCIFS/SMBクライアントは、テイクオーバーの発生時と、セッションで使用されているアグリゲートがアグリゲートのホームノードにギブバックされる際に、セッションが失われます。これはCIFS/SMBプロトコル自体によって課せられる制限です。テイクオーバーとギブバックに起因する問題を回避するには、承認済みのサードパーティ製品をご使用ください。ご不明な点がございましたら、 NetAppサポートまでお問い合わせください。


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["継続的可用性を備えたSMB共有"^]非中断運用はCloud Volumes ONTAPではサポートされていません。
