---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP には、信頼性の高い運用を実現するために、Google Cloud でのストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。 
---
= Google Cloud のCloud Volumes ONTAPのストレージ制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、信頼性の高い操作を実現するためのストレージ構成の制限があります。最高のパフォーマンスを得るには、システムを最大値で構成しないでください。



== ライセンスによる最大システム容量

Cloud Volumes ONTAPシステムの最大システム容量は、ライセンスによって決まります。最大システム容量には、ディスクベースのストレージと、データ階層化に使用されるオブジェクト ストレージが含まれます。

NetApp はシステム容量制限の超過をサポートしていません。ライセンス容量の制限に達した場合、 BlueXP はアクションが必要なメッセージを表示し、追加のディスクを追加できなくなります。

一部の構成では、ディスク制限により、ディスクのみを使用して容量制限に達することができません。容量制限に達するには https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["非アクティブなデータをオブジェクトストレージに階層化する"^]。詳細については、以下のディスク制限を参照してください。

.容量ベースのライセンスの容量制限
容量ベースのライセンスにより、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された合計容量は、クラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。参照 https://cloud.google.com/storage/docs/buckets["Google Cloud ドキュメント"^]詳細についてはこちらをご覧ください。

他のライセンスタイプの容量制限::


[cols="25,75"]
|===
| ライセンス | 最大システム容量（ディスク + オブジェクト ストレージ） 


| フリーミアム | 500 GB 


| PAYGO 探索 | 2 TB (Explore ではデータ階層化はサポートされていません) 


| PAYGOスタンダード | 10 TB 


| PAYGOプレミアム | 368 TB 


| ノードベースのライセンス | 2 PiB（複数のライセンスが必要） 
|===
.HA ペアの場合、ライセンス容量の制限はノードごとですか、それとも HA ペア全体に対してですか?
容量制限は HA ペア全体に適用されます。ノードごとではありません。たとえば、プレミアム ライセンスを使用する場合、両方のノード間で最大 368 TB の容量を持つことができます。

.HA ペアの場合、ミラーリングされたデータはライセンス容量制限にカウントされますか?
いいえ、違います。HA ペアのデータはノード間で同期的にミラーリングされるため、Google Cloud で障害が発生した場合でもデータを利用できます。たとえば、ノード A で 8 TB のディスクを購入した場合、 BlueXP はミラーリングされたデータに使用されるノード B にも 8 TB のディスクを割り当てます。16 TB の容量が設定されていますが、ライセンス制限にカウントされるのは 8 TB のみです。



== アグリゲートの制限

Cloud Volumes ONTAPは、Google Cloud Platform ディスクを _アグリゲート_ にグループ化します。アグリゲートはボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限 


| データ集約の最大数 ^1^  a| 
* 単一ノードの場合は99
* HAペア全体で64




| 最大集約サイズ | 256 TB の生の容量 ^2^ 


| アグリゲートあたりのディスク数 | 1-6 ^3^ 


| アグリゲートあたりの RAID グループの最大数 | 1 
|===
注：

. データ集約の最大数にはルート集約は含まれません。
. アグリゲートを構成するディスクによって、アグリゲートの容量制限が決まります。この制限には、データ階層化に使用されるオブジェクト ストレージは含まれません。
. アグリゲート内のすべてのディスクは同じサイズである必要があります。




== ディスクと階層化の制限

以下の表は、ディスクのみを使用した場合の最大システム容量、およびディスクとオブジェクト ストレージへのコールド データ階層化を使用した場合の最大システム容量を示しています。ディスク制限は、ユーザー データが含まれるディスクに固有です。制限にはブート ディスク、ルート ディスク、 NVRAM は含まれません。

[cols="60,40"]
|===
| パラメータ | 制限 


| 最大データディスク  a| 
* 単一ノードシステムの場合は124
* HAペアの場合、ノードあたり123




| 最大ディスクサイズ | 64 TB 


| ディスクのみの最大システム容量 | 256 TB ^1^ 


| ディスクと Google Cloud Storage バケットへのコールドデータ階層化による最大システム容量 | ライセンスによって異なります。上記の最大システム容量制限を参照してください。 
|===
^1^ この制限は、Google Cloud Platform の仮想マシンの制限によって定義されます。



== ストレージVMの制限

一部の構成では、Cloud Volumes ONTAP用の追加のストレージ VM (SVM) を作成できます。

これらはテストされた制限です。追加のストレージ VM の構成はサポートされていません。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["追加のストレージVMを作成する方法を学ぶ"^] 。

[cols="2*"]
|===
| ライセンス タイプ | ストレージVMの制限 


| *フリーミアム*  a| 
合計 24 台のストレージ VM ^1^



| *容量ベースのPAYGOまたはBYOL* ^2^  a| 
合計 24 台のストレージ VM ^1^



| *ノードベースのBYOL* ^3^  a| 
合計 24 台のストレージ VM ^1^



| *ノードベースのPAYGO*  a| 
* データを提供するための 1 つのストレージ VM
* 災害復旧用のストレージVM 1台


|===
. これら 24 台のストレージ VM は、データを提供したり、災害復旧 (DR) 用に構成したりできます。
. 容量ベースのライセンスの場合、追加のストレージ VM に対して追加のライセンス コストは発生しませんが、ストレージ VM ごとに 4 TiB の最小容量料金が発生します。たとえば、2 つのストレージ VM を作成し、それぞれに 2 TiB のプロビジョニングされた容量がある場合、合計 8 TiB が課金されます。
. ノードベースの BYOL の場合、 Cloud Volumes ONTAPにデフォルトで付属する最初のストレージ VM を超える追加のデータ提供ストレージ VM ごとにアドオン ライセンスが必要です。ストレージ VM アドオン ライセンスを取得するには、アカウント チームにお問い合わせください。
+
災害復旧 (DR) 用に構成するストレージ VM にはアドオン ライセンスは必要ありません (無料) が、ストレージ VM の制限にカウントされます。たとえば、データ サービス ストレージ VM が 12 台、災害復旧用にストレージ VM が 12 台構成されている場合、制限に達しているため、追加のストレージ VM を作成することはできません。





== 論理ストレージの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限 


.2+| *ファイル* | 最大サイズ ^2^ | 128 TB 


| ボリュームあたりの最大数 | ボリューム サイズに依存、最大20億個 


| * FlexCloneボリューム* | 階層的クローンの深さ ^12^ | 499 


.3+| * FlexVolボリューム* | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ ^3^ | 300TiB 


| *Qtrees* | FlexVolあたりの最大数 | 4,995 


| *スナップショットコピー* | FlexVolあたりの最大数 | 1,023 
|===
. 階層クローンの深さは、単一のFlexVol volumeから作成できるFlexCloneボリュームのネストされた階層の最大深さです。
. ONTAP 9.12.1P2以降では、上限は128TBです。ONTAP 9.11.1以前のバージョンでは、上限は16TBです。
. 最大サイズ 300 TiB までのFlexVol volumeの作成は、次のツールと最小バージョンを使用してサポートされます。
+
** Cloud Volumes ONTAP 9.12.1 P2 および 9.13.0 P2 以降の System Manager およびONTAP CLI
** Cloud Volumes ONTAP 9.13.1 以降のBlueXP






== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSIストレージ | パラメータ | 制限 


.4+| *LUN* | ノードあたりの最大数 | 1,024 


| LUNマップの最大数 | 1,024 


| 最大サイズ | 16 TB 


| ボリュームあたりの最大数 | 512 


| *igroups* | ノードあたりの最大数 | 256 


.2+| *イニシエーター* | ノードあたりの最大数 | 512 


| igroupあたりの最大数 | 128 


| *iSCSIセッション* | ノードあたりの最大数 | 1,024 


.2+| *LIF* | ポートあたりの最大数 | 1 


| ポートセットあたりの最大数 | 32 


| *ポートセット* | ノードあたりの最大数 | 256 
|===


== Cloud Volumes ONTAP HAペアは即時ストレージギブバックをサポートしていません

ノードが再起動した後、パートナーはストレージを返す前にデータを同期する必要があります。データの再同期にかかる時間は、ノードがダウンしている間にクライアントによって書き込まれたデータの量と、ギブバック時のデータ書き込み速度によって異なります。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Google Cloud で実行されるCloud Volumes ONTAP HA ペアのストレージの仕組みを学びます"^] 。
